name: On Push

on:
  push:
    tags:
      - "*"

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Contents
        uses: actions/checkout@v2    
      - name: Updating Change-Log
        uses: varunsridharan/action-change-log-updater@master
        with:
          REPO_NAME: "wponion/docs"
          REMOTE_FILE: "others/change-log.md"
          LOCAL_FILE: "CHANGELOG.md"
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          
  upload_assets:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Composer
        uses: nanasess/composer-installer-action@master
      - name: Create Github Release Archive
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          mkdir dist/
          composer install --no-dev && git archive -o dist/"$VERSION.zip"  HEAD && zip -gr dist/"$VERSION.zip" vendor/
      - name: Upload To Github
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  upload_demo:
    runs-on: ubuntu-latest
    steps:
    - name: Fetching Contents
      uses: actions/checkout@v2
    - name: Installing Composer
      uses: pxgamer/composer-action@master
      with:
        command: install --no-dev
    - name: Uploading To FTP
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
