name: WPOnion Downloader

on:
  issue_comment:
    types: [created, deleted]
  schedule:
    - cron: "0/15 * * * *"
  push:
    branches:
      - master

jobs:
  Downloader:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Repository
        uses: actions/checkout@v1
      - name: Installing Composer
        uses: nanasess/composer-installer-action@master
      - name: WPOnion Downloader
        run: |
          echo "##[group] Removing Old Source"
          rm -rf wponion/
          rm -rf stable/ 
          rm -rf development/
          echo "##[endgroup]"

          echo "##[group] WPOnion Stable Clone"
          git clone https://github.com/wponion/wponion stable
          echo "##[endgroup]"

          echo "##[group] Installing Required Libs"
          cd stable && ls -lah && composer install --no-dev && cd ../
          echo "##[endgroup]"

          echo "
          
          "

          echo "##[group] WPOnion Development Clone"
          git clone --branch development https://github.com/wponion/wponion development
          echo "##[endgroup]"

          echo "##[group] Installing Required Libs"
          cd development && ls -lah && composer install --no-dev && cd ../
          echo "##[endgroup]"
      - name: Updating Current Repo
        run: |
            rm -rf wponion/.git
            rm -rf stable/.git
            rm -rf development/.git
            git config --global user.email "wponion@gmail.com"
            git config --global user.name "WPOnion Downloader"
            git add -A
            git commit -m "WPOnion Stable & Development Source Updated"
            git push "https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY" HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
